services:
  spark-master:
    build: ./master
    container_name: spark-master
    env_file:
      - ./master/.env
    ports:
      - "7077:7077"  # porta do master
      - "8080:8080"  # interface web do Spark
    networks:
      - spark-network

  spark-worker:
    build: ./worker
    container_name: spark-worker
    env_file:
      - ./worker/.env
    ports:
      - "8081:8081"  # interface web do worker
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
